# Generated by Django 5.1 on 2026-01-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_coupon_order_handled_by_order_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
